# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sunjie/SlabHash

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sunjie/SlabHash

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/sunjie/SlabHash && $(CMAKE_COMMAND) -E cmake_progress_start /home/sunjie/SlabHash/CMakeFiles /home/sunjie/SlabHash/storage//CMakeFiles/progress.marks
	cd /home/sunjie/SlabHash && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 storage/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sunjie/SlabHash/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/sunjie/SlabHash && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 storage/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/sunjie/SlabHash && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 storage/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/sunjie/SlabHash && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 storage/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/sunjie/SlabHash && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
storage/CMakeFiles/edgeweightsampler.dir/rule:
	cd /home/sunjie/SlabHash && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 storage/CMakeFiles/edgeweightsampler.dir/rule
.PHONY : storage/CMakeFiles/edgeweightsampler.dir/rule

# Convenience name for target.
edgeweightsampler: storage/CMakeFiles/edgeweightsampler.dir/rule

.PHONY : edgeweightsampler

# fast build rule for target.
edgeweightsampler/fast:
	cd /home/sunjie/SlabHash && $(MAKE) $(MAKESILENT) -f storage/CMakeFiles/edgeweightsampler.dir/build.make storage/CMakeFiles/edgeweightsampler.dir/build
.PHONY : edgeweightsampler/fast

Storage_mode.o: Storage_mode.cc.o

.PHONY : Storage_mode.o

# target to build an object file
Storage_mode.cc.o:
	cd /home/sunjie/SlabHash && $(MAKE) $(MAKESILENT) -f storage/CMakeFiles/edgeweightsampler.dir/build.make storage/CMakeFiles/edgeweightsampler.dir/Storage_mode.cc.o
.PHONY : Storage_mode.cc.o

Storage_mode.i: Storage_mode.cc.i

.PHONY : Storage_mode.i

# target to preprocess a source file
Storage_mode.cc.i:
	cd /home/sunjie/SlabHash && $(MAKE) $(MAKESILENT) -f storage/CMakeFiles/edgeweightsampler.dir/build.make storage/CMakeFiles/edgeweightsampler.dir/Storage_mode.cc.i
.PHONY : Storage_mode.cc.i

Storage_mode.s: Storage_mode.cc.s

.PHONY : Storage_mode.s

# target to generate assembly for a file
Storage_mode.cc.s:
	cd /home/sunjie/SlabHash && $(MAKE) $(MAKESILENT) -f storage/CMakeFiles/edgeweightsampler.dir/build.make storage/CMakeFiles/edgeweightsampler.dir/Storage_mode.cc.s
.PHONY : Storage_mode.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... edgeweightsampler"
	@echo "... Storage_mode.o"
	@echo "... Storage_mode.i"
	@echo "... Storage_mode.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/sunjie/SlabHash && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

